### ISSUE TITLE
Export additional types

### ISSUE THREAD

**Issue by pierreis** [grissius/protocat#26]
Currently, the `ProtoCatCall` type is not exported from the public API, which requires the service implementer to either:

- Type it as any and loose type safety entirely
- Write his own type mimicking ProtoCat's one

Could we expose this type (and possibly others I can't think of) from the public API?

**Comment by grissius** [comment]
Sure we could. I will try to get to it early next week, but feel free to post a PR.

As a current workaround until next realease, which is unaesthetic, but better than `any` or `copy-paste` is to import from dist subdir.

```typescript
import { ProtoCatCall } from 'protocat/dist/lib/server/call'
```

Thanks for reporting 👍

**Comment by grissius** [comment]
Released under 0.5.2 :rocket:

**Comment by pierreis** [comment]
Thanks!

**Comment by pierreis** [comment]
Thanks!
