### ISSUE TITLE
Custom client feature request

### ISSUE THREAD

**Issue by iamguid** [grissius/protocat#43]
[Twirp](https://github.com/hopin-team/twirp-ts) have cool feature, custom client, see docs https://github.com/hopin-team/twirp-ts#twirp-client
I think it is important, only one way to testing that I see is replace client to custom implementation and use something like [supertest](https://github.com/ladjs/supertest) in that implementation, what do you think about testing endpoints using that way? Maybe you can get me advice on how to testing endpoints in your library?

Protorespect for the library, thank you!

**Comment by iamguid** [comment]
Hm, maybe i can just run client in nodejs environment, i will try it. But it will be nice if you add "how to test" chapter in documentation.

**Comment by iamguid** [comment]
Ok, it works out of the box in nodejs env, I close the issue.

**Comment by grissius** [comment]
Yes, the client is a Node.js client. Feel free to publish a proposal page on testing! The client is still in a prototype phase, when I was not super sure it is the best API to expose.

But eventually I do the same, integration tests using the client (which is the main purpose why the client was added). Protorespect for the issue autoclose.
